# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('incident_dt', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('case', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('report_dt', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='report',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='reports.Report'),
        ),
        migrations.AddField(
            model_name='incident',
            name='station',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='reports.Station'),
        ),
    ]
