# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
