# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='station',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='reports.Station'),
        ),
    ]
