# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170726_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='report_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
