# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20170726_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='arrested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
