# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0006_auto_20170727_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_dt',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('text',
                 models.TextField()),
                ('incident',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='reports.Incident')),
                ('user',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
