# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_incident_tweeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='abbreviation',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='county',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default='37.8272'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default='122.2913'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='zipcode',
            field=models.IntegerField(default='90000'),
            preserve_default=False,
        ),
    ]
