# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('reports', '0009_auto_20170807_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='tags',
            field=taggit.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='report',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='incidents',
                to='reports.Report'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='incidents',
                to='reports.Station'),
        ),
    ]
