# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170807_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
