# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_incident_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
