# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_incident_prohibition_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='warrant',
            field=models.BooleanField(default=False),
        ),
    ]
