# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_incident_warrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='bpd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
