# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_incident_bpd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='raw_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='raw_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
