# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20170808_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='raw_title',
            field=models.CharField(max_length=255),
        ),
    ]
