# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20170809_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='abbreviation',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
